name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.20.2
    - name: Use Node.js 16.13.0
      uses: actions/setup-node@v2
      with:
        node-version: 16.13.0
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Run build
      run: pnpm run build
    - name: Run tests
      run: pnpm run test