name: CI CMake Build and Test

on:
  push:
    paths:
      - 'RPGMPacker/**'
      - 'RPGMPackerLib/**'
      - 'RPGMPackerTests/**'
      - '.github/workflows/**'
      - 'CMakeLists.txt'
      - '**.cmake'
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules
  TARGET: RPGMPacker
  TEST_TARGET: RPGMPackerTests
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  ENABLE_TEST_COVERAGE: 0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: "**/cpm_modules"
        key: ${{ github.workflow }}-cpm-modules-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

    - name: Enable Code Coverage
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "ENABLE_TEST_COVERAGE=1" >> $GITHUB_ENV

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        cmake -E make_directory build/
        cmake -S . -B build/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_TEST_COVERAGE=$ENABLE_TEST_COVERAGE
        cmake --build build/ --config $BUILD_TYPE

    - name: Test (Windows)
      if: matrix.os == 'windows-latest'
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        cd build/$TEST_TARGET/$BUILD_TYPE
        ./$TEST_TARGET.exe
    - name: Test (Ubuntu & macOS)
      if: matrix.os != 'windows-latest'
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        cd build/$TEST_TARGET
        ./$TEST_TARGET

    - name: collect code coverage
      if: matrix.os == 'ubuntu-latest'
      run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"